spring:
  application:
    name: identity-gateway

server:
  port: 8080

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

app:
  cors:
    allowed-origins: http://127.0.0.1:7000,http://localhost:7000