package com.identitygateway.audit;

public enum AuditEventType {
    AUTH_LOGIN_SUCCEEDED,
    AUTH_LOGIN_FAILED,
    AUTH_LOGOUT,
    VERIFICATION_SESSION_CREATED,
    MANUAL_IDENTITY_CAPTURED,
    DIP_CHIP_PAYLOAD_CAPTURED,
    DOPA_VALIDATION_COMPLETED,
    VERIFICATION_CLOSED
}