package com.identitygateway.audit;

public enum AuditEventType {
    AUTH_LOGIN_SUCCEEDED,
    AUTH_LOGIN_FAILED,
    AUTH_LOGOUT,
    AUTH_PASSWORD_CHANGED,
    AUTH_SESSION_REVOKED,
    OPERATOR_CREATED,
    OPERATOR_PASSWORD_CHANGED,
    OPERATOR_DISABLED,
    VERIFICATION_METHOD_STATUS_CHANGED,
    VERIFICATION_SESSION_CREATED,
    MANUAL_IDENTITY_CAPTURED,
    DIP_CHIP_PAYLOAD_CAPTURED,
    DOPA_VALIDATION_COMPLETED,
    VERIFICATION_CLOSED
}
